remote_theme: pmarsceill/just-the-docs
title: Shipwreck Engine 3D Documentation
description: 
just_the_docs:
  show_toc: true  # Table of contents on each page
  toc_levels: 1..3  # Heading levels shown in TOC (1=H1, 2=H2, etc.)
  custom_css:
    - assets/css/custom.css
  # Set the navigation structure
  collections:
    sidebar:
      - title: "Documentation"
        links:
          #- title: "Getting Started"
          #  url: /getting-started/
          #- title: "API Reference"
          #  url: /api-reference/
  search_enabled: true
  search:
    layout: default
