remote_theme: pmarsceill/just-the-docs
title: Shipwreck Engine 3D Documentation
description: 
just_the_docs:
  custom_css:
    - assets/css/custom.css
  # Set the navigation structure
  collections:
    sidebar:
      - title: "Documentation"
        links:
          #- title: "Getting Started"
          #  url: /getting-started/
          #- title: "API Reference"
          #  url: /api-reference/
  search_enabled: true
  search:
    layout: default
